Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2019-05, with the labels that each got.

#8 Fix incorrect references to old repo.
  cmd/agent/main.go
  cmd/client/main.go
  cmd/proxy/main.go
  examples/legacy/client/main.go
  examples/legacy/server/main.go
  pkg/agent/agentclient/client.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
  pkg/agent/client/client.go
  pkg/agent/client/conn.go
  pkg/agent/server/server.go
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9 Fixed license header on proto.
  Makefile
  hack/go-license-header.txt
  proto/agent/agent.pb.go
  proto/agent/agent.proto
  proto/proxy.pb.go
  proto/proxy.proto
Labels: approved, cncf-cla: yes, lgtm, size/M

#11 Adding basic image generation targets.
  Makefile
  README.md
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#13 Allow proxy agent to connect to non local server.
  Makefile
  cmd/agent/main.go
  cmd/proxy/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#14 Implement Close
  pkg/agent/agentclient/client.go
  pkg/agent/agentclient/client_test.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
  pkg/agent/client/client.go
  pkg/agent/client/conn.go
  proto/agent/agent.pb.go
  proto/agent/agent.proto
Labels: approved, cncf-cla: yes, lgtm, size/XL

#16 Added code to get http-connect to work with the test client.
  README.md
  cmd/client/main.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/L
