Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2019-11, with the labels that each got.

#37 fix golint errors
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#38 add multisarch and cloudbuild
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#39 fix Makefile commands
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#40 Fix build makefile
  Makefile
Labels: cncf-cla: yes, ok-to-test, size/XS

#41 Fix missing docker experimental env
  cloudbuild.yaml
Labels: cncf-cla: yes, ok-to-test, size/XS

#35 Add concurrency test
  pkg/agent/client/client.go
  tests/concurrent_test.go
  tests/proxy_test.go
  tests/tcp_server_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
