Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2019-07, with the labels that each got.

#22 Several improvements: unit test, logging, comments
  cmd/client/main.go
  pkg/agent/agentclient/client.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
  pkg/agent/client/client.go
  pkg/agent/client/client_test.go
  pkg/agent/client/conn.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#25 apiserver-network-proxy flags should use kebab-case not camelCase
  Makefile
  README.md
  cmd/agent/main.go
  cmd/client/main.go
  cmd/proxy/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#29 Fix error on DIAL_RSP for http-connect.
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
