Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2020-02, with the labels that each got.

#51 Adding support for server to authenticate agent
  Makefile
  cmd/agent/main.go
  cmd/proxy/main.go
  examples/kubernetes/README.md
  examples/kubernetes/konnectivity-agent.yaml
  examples/kubernetes/konnectivity-server.yaml
  examples/kubernetes/konnectivity-test-client.yaml
  examples/kubernetes/kubeconfig
  examples/kubernetes/token_generation.sh
  go.mod
  go.sum
  pkg/agent/agentclient/clientset.go
  pkg/agent/agentclient/stream.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/server_test.go
  pkg/util/certificates.go
  proto/agent/mocks/agent_mock.go
  proto/header/header.go
  tests/proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#60 updates owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 Do exponential backoff in clientset sync
  cmd/agent/main.go
  pkg/agent/agentclient/clientset.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#59 Move client libraries into separate module
  Makefile
  cmd/client/main.go
  cmd/proxy/main.go
  go.mod
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  konnectivity-client/pkg/client/conn.go
  konnectivity-client/proto/client/client.pb.go
  konnectivity-client/proto/client/client.proto
  pkg/agent/agentclient/client.go
  pkg/agent/agentclient/client_test.go
  pkg/agent/agentclient/stream.go
  pkg/agent/agentclient/stream_test.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
  proto/agent/agent.pb.go
  proto/agent/agent.proto
  proto/agent/mocks/agent_mock.go
  proto/proxy.pb.go
  proto/proxy.proto
  tests/concurrent_test.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
  tests/tcp_server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#65 Fix docker-build
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/client-build.Dockerfile
  artifacts/images/server-build.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Prevent logging packet data in client
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/conn.go
  pkg/agent/agentclient/client.go
  pkg/agent/agentserver/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#67 Add note about importing root module
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#58 Let the proxy server handle concurrent client requests correctly
  pkg/agent/agentserver/backend_manager.go
  pkg/agent/agentserver/backend_manager_test.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/server_test.go
  pkg/agent/agentserver/tunnel.go
  tests/concurrent_client_request_test.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#68 Avoid only listening on localhost for admin server
  cmd/agent/main.go
  examples/kubernetes/konnectivity-agent.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
