Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2020-03, with the labels that each got.

#82 Use the bufrw
  pkg/agent/agentserver/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#78 Fix races
  go.sum
  pkg/agent/agentclient/client.go
  pkg/agent/agentserver/backend_manager.go
  pkg/agent/agentserver/backend_manager_test.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/tunnel.go
  tests/concurrent_client_request_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#75 Fix warning message if agent disconnects
  pkg/agent/agentserver/backend_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#90 Quick return
  pkg/agent/agentclient/client.go
  pkg/agent/agentclient/client_test.go
  pkg/agent/agentserver/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#89 Protect agent connContext
  pkg/agent/agentclient/client.go
  pkg/agent/agentclient/client_test.go
Labels: approved, cncf-cla: yes, size/L

#91 Restructure the directories
  Makefile
  artifacts/images/server-build.Dockerfile
  cmd/agent/main.go
  cmd/server/main.go
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/agent/clientset.go
  pkg/agent/stream.go
  pkg/agent/stream_test.go
  pkg/server/backend_manager.go
  pkg/server/backend_manager_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/tunnel.go
  tests/concurrent_client_request_test.go
  tests/proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#57 Update docs to remove bug with vendor
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#98 add a missing return on error
  pkg/server/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
