Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2020-05, with the labels that each got.

#104 Improve validation to when using SA authentication
  cmd/server/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#93 Close UDS socket connection on completion in GRPC mode
  cmd/client/main.go
  konnectivity-client/pkg/client/client.go
  tests/concurrent_client_request_test.go
  tests/concurrent_test.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
  tests/tcp_server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#106 Turn on race for tests and fix code.
  Makefile
  README.md
  cmd/agent/main.go
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  konnectivity-client/proto/client/client.pb.go
  pkg/agent/client.go
  pkg/agent/clientset.go
  pkg/agent/stream.go
  proto/agent/agent.pb.go
  tests/concurrent_client_request_test.go
  tests/concurrent_test.go
  tests/proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
