Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2020-06, with the labels that each got.

#110 Use protoc-gen-go@v1.3.2
  README.md
  go.mod
  go.sum
  konnectivity-client/proto/client/client.pb.go
  proto/agent/agent.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#102 Implement the readiness check of the proxy server
  cmd/server/main.go
  pkg/server/readiness_manager.go
  pkg/server/server.go
  tests/readiness_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#108 Remove the proxy agent retry logic to simplify the code.
  cmd/agent/main.go
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/agent/clientset.go
  pkg/agent/stream.go
  pkg/agent/stream_test.go
  tests/proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#115 add DNS:localhost to master certificate
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
