Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2020-01, with the labels that each got.

#44 remove uneeded travis ci and golangci
  .golangci.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#47 Adding support for agent authenticate server by using kubeapi-server ca
  Makefile
  README.md
  artifacts/images/client-build.Dockerfile
  cmd/agent/main.go
  cmd/client/main.go
  cmd/proxy/main.go
  examples/kubernetes/README.md
  examples/kubernetes/konnectivity-agent.yaml
  examples/kubernetes/konnectivity-server.yaml
  examples/kubernetes/konnectivity-test-client.yaml
  examples/kubernetes/kubia.yaml
  pkg/util/certificates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#50 Align proxy/main.go's flags naming convention with rest of the project
  cmd/proxy/main.go
  examples/kubernetes/konnectivity-server.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#48 Update reviewers to reflect current contributors.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#46 Make proxy work even if proxy server is HA and is behind a LB
  cmd/agent/main.go
  cmd/proxy/main.go
  go.mod
  go.sum
  pkg/agent/agentclient/client.go
  pkg/agent/agentclient/client_test.go
  pkg/agent/agentclient/clientset.go
  pkg/agent/agentclient/stream.go
  pkg/agent/agentclient/stream_test.go
  pkg/agent/agentserver/server.go
  pkg/agent/agentserver/server_test.go
  pkg/agent/agentserver/tunnel.go
  proto/header/header.go
  tests/concurrent_test.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
  tests/tcp_server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#54 Fix a typo in the makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#52 minor fixes
  cmd/agent/main.go
  cmd/proxy/main.go
  pkg/agent/agentclient/clientset.go
  pkg/agent/agentclient/stream.go
Labels: approved, cncf-cla: yes, lgtm, size/M
