Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2020-07, with the labels that each got.

#118 Add metrics to the proxy agent
  cmd/agent/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/agent/client.go
  pkg/agent/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#120 Add proxy server metrics
  pkg/server/metrics/metrics.go
  pkg/server/server.go
  pkg/server/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#119 Add agent dial latency metrics
  pkg/agent/client.go
  pkg/agent/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#124 Added controllable test http server.
  Makefile
  README.md
  artifacts/images/test-server-build.Dockerfile
  cmd/client/main.go
  cmd/test-server/main.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#122 Enable pprof in proxy server
  cmd/server/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#121 Add an option to delete existing UDS file before listening on it
  cmd/server/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#125 Disconnect frontend if backend drops
  pkg/server/server.go
  tests/agent_disconnect_test.go
  tests/proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#128 Make certs gen work on macOS Catalina
  Makefile
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#134 Increase cloudbuild timeout
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#135 fix typo in docker push
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 Fixes minor interface assertion
  pkg/server/backend_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#131 Test konnectivity-client in make test and fix tests
  Makefile
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
