Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2021-08, with the labels that each got.

#253 Fix cleanup of timeout on dial request.
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/conn.go
  konnectivity-client/proto/client/client.pb.go
  konnectivity-client/proto/client/client.proto
  pkg/server/server.go
  proto/agent/mocks/agent_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#254 Updated server.go to include metrics for pending dial requests
  pkg/server/metrics/metrics.go
  pkg/server/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#248 Enable http2 health checking with go 1.16.5
  cmd/client/main.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#257 add agent to backends after it is authenticated
  pkg/server/server.go
  pkg/server/server_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#258 Updates K8s dependency from v0.19.10 to v0.20.10.
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved
