Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2021-11, with the labels that each got.

#281 Bubble up errors on grpc connections.
  pkg/server/server.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#277 Added block check to agent xfer channel.
  cmd/agent/app/options/options.go
  pkg/agent/client.go
  pkg/agent/clientset.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#284 Ran go mod tidy
  go.sum
Labels: lgtm, size/XS, cncf-cla: yes, approved

#287 Make sure deps are clean prior to running update vendor.
  RELEASE.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#288 Remove cpu limit from example agent pod.
  examples/kubernetes/konnectivity-agent.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved

#282 add option to change cipher suites
  cmd/agent/app/options/options.go
  cmd/server/app/options/options.go
  cmd/server/app/server.go
  go.mod
  pkg/agent/clientset.go
  pkg/util/net.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#291 Update to grpc 1.42.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#289 konnectivity-client: improve logs for DIAL_RSP not recognized case.
  konnectivity-client/pkg/client/client.go
  pkg/server/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#290 Don't leak konn-client connections if DialResp is not recognized
  konnectivity-client/pkg/client/client.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#285 proxy-agent: support new SyncForever mode.
  cmd/agent/app/options/options.go
  pkg/agent/clientset.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#274 use docker buildx to build multi-arch image
  Makefile
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#297 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved

#298 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved
