Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2021-06, with the labels that each got.

#205 replace 127.0.0.1 by PROXY_SERVER_IP in agent and server-proxy's certs
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#230 Fix lint errors.
  go.sum
  pkg/server/metrics/metrics.go
  proto/agent/mocks/agent_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#225 Add metrics for showing the number of backend agents connected to metric server
  pkg/server/backend_manager.go
  pkg/server/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#227 refine cmd/agent/main.go and cmd/server/main.go
  cmd/agent/app/options/options.go
  cmd/agent/app/server.go
  cmd/agent/main.go
  cmd/server/app/options/options.go
  cmd/server/app/server.go
  cmd/server/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#231 Fixed readiness url path to be /readyz
  cmd/agent/app/server.go
  cmd/server/app/server.go
  cmd/server/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#235 Fix the wrong command in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#242 proxy-test-client record number of failed request
  cmd/client/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#241 capture the loop variable in the proxy-test-client
  Makefile
  cmd/client/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#245 add DefaultRoute strategy to validation
  cmd/server/app/options/options.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#238 Add context to CreateSingleUseGrpcTunnel.
  cmd/client/main.go
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  proto/agent/mocks/agent_mock.go
  tests/agent_disconnect_test.go
  tests/concurrent_client_request_test.go
  tests/concurrent_test.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
  tests/tcp_server_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#243 remove unused code in server
  Makefile
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S
