Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2021-07, with the labels that each got.

#246 update to latest go to pickup critical http2 connection fixes
  artifacts/images/agent-build.Dockerfile
  artifacts/images/client-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#179 Make dial request processing asynchonous.
  pkg/agent/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#251 Fixed race condition writing to closed channel
  pkg/agent/client.go
Labels: approved, cncf-cla: yes, lgtm, size/S
