Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2021-05, with the labels that each got.

#199 Trivial: make agent log level more consistent with server.
  pkg/agent/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#201 Added pprof support to the Proxy Agent.
  cmd/agent/main.go
  cmd/server/main.go
  pkg/util/handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#204 Add proxy-server current connections metric.
  pkg/server/metrics/metrics.go
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#203 Always remove client when Serve() returns
  pkg/agent/client.go
  tests/reconnect_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#211 Clean up client testing.
  cmd/client/main.go
  pkg/agent/client.go
  pkg/server/server.go
  pkg/server/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#213 fix error msg
  pkg/server/backend_manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#218 Add a timeout to prevent deadlock
  konnectivity-client/pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#216 upgrade client-go package from v0.17.1 to v0.19.10,
  go.mod
  go.sum
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#220 Use more efficient timer pattern.
  konnectivity-client/pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#221 Improve handling of repeated dial response.
  konnectivity-client/pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, size/S
