Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2022-08, with the labels that each got.

#371 Update to go 1.17.12 to fix various security issues
  artifacts/images/agent-build.Dockerfile
  artifacts/images/client-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#374 Fix HA test to be re-runnable
  tests/ha_proxy_server_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#380 Test cleanup
  tests/agent_disconnect_test.go
  tests/concurrent_client_request_test.go
  tests/concurrent_test.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
  tests/readiness_test.go
  tests/reconnect_test.go
  tests/tcp_server_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#384 Log dial errors on the agent as well as the server
  pkg/agent/client.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#386 Handle broken dial in agent.
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/server/server.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#389 [konnectivity-client] Expose dial failure reasons
  konnectivity-client/pkg/client/client.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#390 Adjust proxy-server agent KeepaliveEnforcementPolicy
  cmd/server/app/server.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#391 Fix race conditions in client tests
  konnectivity-client/pkg/client/client_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#363 Make proxy server bind addresses configurable
  cmd/server/app/options/options.go
  cmd/server/app/server.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#385 Dial Timeout testing improvements
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  tests/agent_disconnect_test.go
  tests/concurrent_test.go
  tests/main_test.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved
