Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2022-12, with the labels that each got.

#420 Adjust server log verbosity to improve signal:noise
  pkg/server/backend_manager.go
  pkg/server/server.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#421 Agent: log dialID in DIAL_REQ handling.
  pkg/agent/client.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#425 Add rudimentary data transfer benchmark tests
  tests/benchmarks_test.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#433 Fixed admin port listen code.
  cmd/agent/app/options/options.go
  cmd/agent/app/options/options_test.go
  cmd/agent/app/server.go
  cmd/server/app/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#432 Update go.mod to be more conservative.
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#423 More metrics
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  konnectivity-client/pkg/client/conn.go
  konnectivity-client/pkg/client/metrics/metrics.go
  konnectivity-client/pkg/common/metrics/metrics.go
  pkg/agent/client.go
  pkg/agent/clientset.go
  pkg/agent/metrics/metrics.go
  pkg/server/backend_manager.go
  pkg/server/metrics/metrics.go
  pkg/server/server.go
  pkg/testing/metrics/metrics.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XL

#422 Fix segfault on empty packet
  pkg/agent/client.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#437 konnectivity-client: lower goleak version in release-0.0 branch.
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#434 Upgraded our GPRC and ProtoBuf libraries.
  Makefile
  README.md
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  konnectivity-client/proto/client/client.pb.go
  konnectivity-client/proto/client/client_grpc.pb.go
  proto/agent/agent.pb.go
  proto/agent/agent_grpc.pb.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#435 Add more pprof functions to server and agent’s admin server
  .gitignore
  cmd/agent/app/server.go
  cmd/server/app/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#438 konnectivity-client: add dial failures metric by reason.
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  konnectivity-client/pkg/client/metrics/metrics.go
  konnectivity-client/pkg/common/metrics/testing/metrics.go
  tests/main_test.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#440 Makefile: fix `make gen`.
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#442 Fix broken `make lint`.
  Makefile
  cmd/agent/app/options/options_test.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#441 konnectivity-client: add a client connections gauge metric.
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  konnectivity-client/pkg/client/metrics/metrics.go
  konnectivity-client/pkg/common/metrics/testing/metrics.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#444 Prepare 0.0.34
  .gitignore
  Makefile
  cmd/agent/app/options/options_test.go
  cmd/agent/app/server.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  konnectivity-client/pkg/client/metrics/metrics.go
  konnectivity-client/pkg/common/metrics/testing/metrics.go
  tests/main_test.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#436 Update server and agent to 1.18.9
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#446 Trim obsolete docker images (test-only).
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#447 Release picks
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#448 Agent: increase log quality.
  pkg/agent/client.go
  pkg/agent/clientset.go
Labels: size/M, lgtm, cncf-cla: yes, approved
