Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2022-02, with the labels that each got.

#320 Add arm64 into RELEASE_ARCH_LIST
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#313 Agent: Add flag for health server listen address
  cmd/agent/app/options/options.go
  cmd/agent/app/server.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#305 Re-work of #252 - make dial request handling async
  pkg/agent/client.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#317 chore: reduce annoying error message
  pkg/agent/client.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#328 konnectivity-client: ensure Close() is called for grpc.ClientConn in CreateSingleUseGrpcTunnel
  konnectivity-client/pkg/client/client.go
Labels: lgtm, size/XS, cncf-cla: yes, approved
