Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2022-09, with the labels that each got.

#395 [konnectivity-client] Fix GetDialFailureReason
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#381 update go modules
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  cmd/agent/app/server.go
  cmd/server/app/server.go
  cmd/test-server/main.go
  go.mod
  go.sum
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, approved, ok-to-test, size/XL

#392 Added goroutine labels to goroutine calls.
  Makefile
  cmd/agent/app/server.go
  cmd/client/main.go
  cmd/server/app/server.go
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/agent/clientset.go
  pkg/server/server.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#398 [konnectivity-client] Ensure grpc tunnel is closed on dial failure
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
  konnectivity-client/pkg/client/conn.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XL

#343 Simple konn-client cleanups
  konnectivity-client/pkg/client/client.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#405 Update goleak library, and remove some unused dependencies
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  konnectivity-client/pkg/client/client_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#407 readme updated with the latest link
  CONTRIBUTING.md
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#402 Improve server logging, especially around initial dial
  pkg/agent/client.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#409 ServerID & AgentID logging cleanup
  cmd/agent/app/options/options.go
  cmd/server/app/options/options.go
  pkg/agent/client.go
  pkg/agent/clientset.go
  pkg/server/server.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#400 Dial metrics
  pkg/server/metrics/metrics.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/testing/metrics/metrics.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved
