Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2022-03, with the labels that each got.

#337 konnectivity-client: fix race condition with pending dials leading to goroutine leaks
  konnectivity-client/pkg/client/client.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#339 Avoid race between serve loop and DialContext receiving dial result
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/client_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#336 Add goroutine leak tests
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  konnectivity-client/pkg/client/client_test.go
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#329 Fix misleading log messages in proxy server when sending DIAL_REQ and CLOSE_REQ
  pkg/server/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#345 Update golang version as part of security fix.
  artifacts/images/agent-build.Dockerfile
  artifacts/images/client-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#347 Add the -v flag to go build in Dockerfiles.
  artifacts/images/agent-build.Dockerfile
  artifacts/images/client-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#348 Update go version to fix CVE-2022-24921.
  artifacts/images/agent-build.Dockerfile
  artifacts/images/client-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: needs-ok-to-test, lgtm, size/XS, cncf-cla: yes, approved
