Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-09, with the labels that each got.

#518 update information about versions and releases
  README.md
  RELEASE.md
Labels: size/M, lgtm, cncf-cla: yes, approved

#522 Pick up CVE fixes (bump to golang 1.19.13).
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#520 Refactor integration tests to prepare for proxy-server & agent skew testing
  tests/agent_disconnect_test.go
  tests/benchmarks_test.go
  tests/concurrent_client_request_test.go
  tests/concurrent_test.go
  tests/framework/agent.go
  tests/framework/framework.go
  tests/framework/proxy_server.go
  tests/ha_proxy_server_test.go
  tests/main_test.go
  tests/proxy_test.go
  tests/readiness_test.go
  tests/reconnect_test.go
  tests/tcp_server_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL
