Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-04, with the labels that each got.

#479 test: fix race condition
  pkg/agent/client_test.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#456 konnectivity-client: code cleanup.
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/conn.go
  pkg/agent/client.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#475 fix: error propagation in http-connect mode
  pkg/server/server.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#465 Document branching & go.mod update strategies
  README.md
  RELEASE.md
Labels: size/S, lgtm, cncf-cla: yes, approved, tide/merge-method-squash

#482 Makefile: declare more 'go build' source dependencies.
  Makefile
Labels: size/S, lgtm, cncf-cla: yes, approved
