Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-10, with the labels that each got.

#526 Refresh reviewers.
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved

#525 proxy-server: strengthen the Backend interface.
  pkg/server/backend_manager.go
  pkg/server/backend_manager_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  proto/header/header.go
  proto/header/header_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#531 Update golang.org/x/net to v0.17.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#533 Update golang.org/x/net to v0.17.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#532 Update golang.org/x/net to v0.17.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#530 Upgrade grpc/http to fix CVE-2023-44487
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test
