Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-01, with the labels that each got.

#424 Trim unused proto.
  konnectivity-client/proto/client/client.pb.go
  konnectivity-client/proto/client/client.proto
Labels: lgtm, cncf-cla: yes, size/L, approved

#451 konnectivity-client: add Send and Recv wrappers to simplify metrics.
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/conn.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#417 Close backend connection when frontend is not found
  konnectivity-client/pkg/client/client.go
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  tests/concurrent_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, tide/merge-method-squash

#453 Metrics bugfix: restore ObservePacket.
  konnectivity-client/pkg/client/client.go
  pkg/agent/client.go
  pkg/server/backend_manager.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#454 [release-0.0 branch] Backports from 0.1.1
  RELEASE.md
  konnectivity-client/pkg/client/client.go
  konnectivity-client/pkg/client/conn.go
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/agent/clientset.go
  pkg/server/backend_manager.go
  pkg/server/metrics/metrics.go
  pkg/server/server.go
  pkg/server/server_test.go
  tests/concurrent_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XL

#414 Cosmetic: avoid "ctx" naming confusion.
  pkg/agent/client.go
  pkg/agent/client_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#457 Update dependencies to patch CVEs
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test
