Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-05, with the labels that each got.

#487 bump prometheus/client_golang to 1.11.1
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#481 Prevent docker build flakes.
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#483 Trivial rename: clarify test-only client.
  Makefile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  cmd/test-client/main.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#486 proxy-server: pure rename (frontends vs. established).
  pkg/server/server.go
  pkg/server/server_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#489 Fix admin bind address description
  cmd/server/app/options/options.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#488 Use distroless
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#490 Bump golang from 1.19.6 to 1.19.9 (CVE fixes)
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#492 Fixed: use dl.k8s.io, not kubernetes-release bucket
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup, ok-to-test
