Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-08, with the labels that each got.

#485 agent: smarter readiness check
  cmd/agent/app/server.go
  pkg/agent/readiness.go
  tests/proxy_test.go
  tests/readiness_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#507 add myself as reviewer and approver
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#511 fix: metric frontend_write_duration_seconds has wrong value
  pkg/server/server.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#508 update genproto
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#514 proxy-server: Wrap Backend more completely.
  pkg/server/backend_manager.go
  pkg/server/backend_manager_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  proto/header/header.go
  tests/concurrent_client_request_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved
