Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-02, with the labels that each got.

#460 proxy-server: synchronization improvements
  pkg/server/server.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#463 konnectivity-server: synchronization cleanup.
  konnectivity-client/pkg/client/client.go
  pkg/agent/client.go
  pkg/server/backend_manager.go
  pkg/server/server.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#427 [server] Block Proxy from returning on both go-routines exiting
  pkg/server/server.go
  pkg/server/server_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#466 proxy-server: fix removeFrontend race.
  pkg/server/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#468 Update golang.org/x/net to v0.7.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#469 Update server and agent images to Go version 1.19.6
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  go.mod
Labels: lgtm, size/XS, cncf-cla: yes, approved

#470 Add server "established_connections" metric.
  pkg/server/metrics/metrics.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/testing/metrics/metrics.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#459 Concurrent cancelled requests test
  pkg/testing/metrics/metrics.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#471 proy-server: always emit backends count metric
  pkg/server/backend_manager.go
  pkg/server/server_test.go
  pkg/testing/metrics/metrics.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#467 proxy-server: improve connection cleanup on client cancel.
  pkg/server/server.go
  pkg/server/server_test.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#472 [release-0.0] Backports from 0.1.2
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  konnectivity-client/pkg/client/client.go
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/server/backend_manager.go
  pkg/server/metrics/metrics.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/testing/metrics/metrics.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL
