Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-11, with the labels that each got.

#535 Configure Dependabot for automatic Docker and Gomod updates
  .github/dependabot.yml
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#539 Mitigate CVEs
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#540 Backport CVE fixes to release-0.28
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved
