Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2023-07, with the labels that each got.

#497 Enable coverage measurement
  .gitignore
  Makefile
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#506 golangci-lint: update due to high resource usage bug
  Makefile
  pkg/agent/client.go
  pkg/server/server.go
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#504 Fix: ciphersuites length equals to 1(expecting 0) when using the default value.
  cmd/server/app/options/options.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#505 bump k8s dependencies to 1.27
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test
