Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2024-04, with the labels that each got.

#605 Fix lint: upgrade to first version that supports go1.21
  Makefile
  cmd/server/app/server.go
  cmd/test-server/main.go
  pkg/server/backend_manager.go
  pkg/server/default_route_backend_manager.go
  tests/agent_disconnect_test.go
  tests/framework/agent.go
  tests/framework/proxy_server.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#607 Fix 'kind' example manifests.
  .github/workflows/e2e.yaml
  examples/kind/README.md
  examples/kind/konnectivity-agent-ds.yaml
  examples/kind/konnectivity-server.yaml
Labels: size/S, lgtm, cncf-cla: yes, approved

#603 Trim duplicate code (related to default route backend storage).
  pkg/server/backend_manager.go
  pkg/server/backend_manager_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#608 Replace Backend interface with a struct.
  pkg/server/backend_manager.go
  pkg/server/backend_manager_test.go
  pkg/server/default_route_backend_manager.go
  pkg/server/desthost_backend_manager.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#613 CVE-2023-45288: update golang.org/x/net to 1.23.0
  Makefile
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, approved, ok-to-test, size/XL

#617 [release-0.30] Fix lint: upgrade to first version that supports go1.21
  Makefile
  cmd/server/app/server.go
  cmd/test-server/main.go
  pkg/server/backend_manager.go
  pkg/server/default_route_backend_manager.go
  tests/agent_disconnect_test.go
  tests/framework/agent.go
  tests/framework/proxy_server.go
  tests/ha_proxy_server_test.go
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#616 lint: skip vendors directory.
  .golangci.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved

#614 CVE-2023-45288 (release-0.30): update golang.org/x/net to 1.23.0
  .golangci.yaml
  Makefile
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, approved, ok-to-test, size/XXL

#621 [release-0.28] CVE-2023-45288: update golang.org/x/net to 1.23.0
  go.mod
  go.sum
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#622 [release-0.1] CVE-2023-45288: update golang.org/x/net to 1.23.0
  go.mod
  go.sum
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test
