Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2024-01, with the labels that each got.

#550 Update go to 1.21
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#552 Run integration tests against an external agent process
  .golangci.yaml
  Makefile
  cmd/agent/app/server.go
  pkg/server/server_test.go
  pkg/testing/metrics/metrics.go
  tests/framework/agent.go
  tests/framework/metrics.go
  tests/framework/proxy_server.go
  tests/main_test.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, tide/merge-method-squash

#553 kind example
  .github/workflows/e2e.yaml
  examples/kind/README.md
  examples/kind/egress_selector_configuration.yaml
  examples/kind/kind.config
  examples/kind/konnectivity-agent-ds.yaml
  examples/kind/konnectivity-server.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XL

#546 Replace golang/mock to uber-go/mock.
  README.md
  go.mod
  go.sum
  pkg/server/backend_manager_test.go
  pkg/server/server_test.go
  proto/agent/mocks/agent_mock.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#559 Disable broken github workflow (e2e).
  .github/workflows/e2e.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved

#555 Fix github action e2e test.
  .github/workflows/e2e.yaml
  examples/kind/konnectivity-agent-ds.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test
