Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2024-03, with the labels that each got.

#573 [release-0.1] Backport CVE fixes.
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#576 [WIP] Added debugging for kubeconfig not loading.
  cmd/server/app/server.go
Labels: size/S, cncf-cla: yes, do-not-merge/work-in-progress, approved

#572 Docker build: parameterize base images.
  .github/workflows/e2e.yaml
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: size/M, lgtm, cncf-cla: yes, approved

#579 Change Dockerfiles (and make targets) to use cross-compile.
  .github/workflows/e2e.yaml
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  examples/kind/konnectivity-agent-ds.yaml
  examples/kind/konnectivity-server.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#582 Set matrix k8s version for e2e ghaction.
  .github/workflows/e2e.yaml
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#581 Publish all architectures.
  Makefile
Labels: size/S, lgtm, cncf-cla: yes, approved

#592 [0.29] [CVE-2024-24786] Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#593 [0.28] [CVE-2024-24786] Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#594 [0.1] [CVE-2024-24786] Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: size/S, lgtm, cncf-cla: yes, approved

#589 Add auto update for github-actions.
  .github/dependabot.yml
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#599 Add test coverage around BackendManager and BackendStorage.
  Makefile
  pkg/server/backend_manager.go
  pkg/server/backend_manager_test.go
  pkg/server/default_route_backend_manager.go
  pkg/server/desthost_backend_manager.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XL

#602 chore: update actions upload-artifact & download-artifact to v4.
  .github/workflows/e2e.yaml
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test
