Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2024-02, with the labels that each got.

#551 [release-0.28] Bump kubernetes deps to v1.28.5
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, approved, ok-to-test, size/XL

#561 [release-0.1] Backport CVEs from release-0.28
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#564 Use nonroot distroless image for agent and server
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#567 Fix `make gen` and rerun it.
  Makefile
  konnectivity-client/proto/client/client.pb.go
  konnectivity-client/proto/client/client_grpc.pb.go
  proto/agent/agent.pb.go
  proto/agent/agent_grpc.pb.go
  proto/agent/mocks/agent_mock.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#569 [release-0.29] Bump k8s deps to v0.29.2
  cmd/agent/app/server.go
  go.mod
  go.sum
  konnectivity-client/go.mod
  konnectivity-client/go.sum
Labels: lgtm, cncf-cla: yes, approved, ok-to-test, size/XL
