Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2024-05, with the labels that each got.

#620 [release-0.29] Update golang to 1.21
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#619 Update golang to 1.22.
  .github/workflows/e2e.yaml
  Makefile
  go.mod
Labels: size/S, lgtm, cncf-cla: yes, approved

#604 ProxyStrategies: code cleanup and improve test coverage.
  cmd/server/app/options/options.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
  pkg/server/backend_manager.go
  pkg/server/backend_manager_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#627 Add readinessProbe for example konnectivity-agent Pod
  examples/kubernetes/konnectivity-agent.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test
