Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2024-06, with the labels that each got.

#628 Nit: go get -> go install in build instructions
  README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#632 Always reset agent connection backoff and enter fast sync when client count < server count
  pkg/agent/clientset.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test, tide/merge-method-squash

#624 Allow configuration of transport channel size in agent and server
  cmd/agent/app/options/options.go
  cmd/agent/app/options/options_test.go
  cmd/server/app/options/options.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
  pkg/agent/client.go
  pkg/agent/clientset.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved, ok-to-test

#631 Add script to quickly deploy kind cluster with custom KNP image
  README.md
  examples/kind-multinode/README.md
  examples/kind-multinode/egress_selector_configuration.yaml
  examples/kind-multinode/quickstart-kind.sh
  examples/kind-multinode/templates/k8s/konnectivity-agent-ds.yaml
  examples/kind-multinode/templates/k8s/konnectivity-server.yaml
  examples/kind-multinode/templates/kind/control-plane.config
  examples/kind-multinode/templates/kind/kind.config
  examples/kind-multinode/templates/kind/worker.config
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test
