Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2025-05, with the labels that each got.

#732 Fix error messages for test-client in UDS mode
  cmd/test-client/main.go
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#736 release-0.32 branch update for v0.32.1 tag
  .github/workflows/e2e.yaml
  cmd/server/app/options/options.go
  cmd/server/app/server.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#737 release-0.31 branch update for v0.31.4 tag
  cmd/server/app/options/options.go
  cmd/server/app/server.go
Labels: size/M, cncf-cla: yes, approved

#738 Bump golangci/golangci-lint-action from 6 to 8
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  cmd/server/app/options/options.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
  tests/framework/proxy_server.go
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#742 Move to go lint 2.1.6
  .github/workflows/golangci-lint.yaml
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#741 Cherry-pick: Bump golangci/golangci-lint-action from 6 to 8
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  Makefile
  cmd/server/app/options/options.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
  tests/framework/proxy_server.go
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#743 Backport to 0.31: Bump golangci/golangci-lint-action from 6 to 8
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  Makefile
  cmd/server/app/options/options.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
  tests/framework/proxy_server.go
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#745 Cherry-pick 0.30: Bump golangci/golangci-lint-action from 6 to 8
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  cmd/agent/app/server.go
  cmd/server/app/options/options.go
  cmd/server/app/options/options_test.go
  cmd/server/app/server.go
  cmd/test-client/main.go
  cmd/test-server/main.go
  pkg/agent/client.go
  pkg/agent/client_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  tests/agent_disconnect_test.go
  tests/custom_alpn_test.go
  tests/framework/proxy_server.go
  tests/proxy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved
