Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2025-01, with the labels that each got.

#684 Updated golang version to 1.23.0
  .github/workflows/golangci-lint.yaml
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
  cmd/server/app/server.go
  go.mod
  go.sum
  konnectivity-client/proto/client/client.pb.go
  pkg/agent/clientset.go
  pkg/agent/clientset_test.go
  pkg/server/backend_manager_test.go
  pkg/server/server_test.go
  proto/agent/mocks/agent_mock.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/proto/client/client.pb.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#696 tests: tweak timings so we cancel during HTTP processing
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#694 tests: print test names during tests
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#685 🐛 Respect log level from the command-line arguments
  cmd/agent/main.go
  cmd/server/main.go
Labels: size/S, lgtm, cncf-cla: yes, approved, ok-to-test

#691 chore: update e2e ci for 1.31 and 1.32
  .github/workflows/e2e.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#699 Updating baseimage to pick up assorted security fixes.
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#697 Fixed comment for connect() return.
  pkg/agent/client.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#701 chore: fix field comments on ClientSet
  pkg/agent/clientset.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#702 Cherry-pick #696 tests: tweak timings so we cancel during HTTP processing
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#705 Updating baseimage to pick up assorted security fixes.
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#703 tests: tweak timings so we cancel during HTTP processing
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#704 tests: tweak timings so we cancel during HTTP processing
  tests/proxy_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#706 Cherrypick to 0.30: Updating baseimage to pick up assorted security fixes.
  Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved
