Repository kubernetes-sigs/apiserver-network-proxy, pull requests merged in 2025-02, with the labels that each got.

#708 Cherry pick to Release 0.29: base image vuln fixes.
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: size/M, lgtm, cncf-cla: yes, approved

#709 Update release-0.31 to x.net 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#717 Cherry-pick 0.29: Change Dockerfiles (and make targets) to use cross-…
  Makefile
  artifacts/images/agent-build.Dockerfile
  artifacts/images/server-build.Dockerfile
  artifacts/images/test-client-build.Dockerfile
  artifacts/images/test-server-build.Dockerfile
Labels: lgtm, cncf-cla: yes, size/L, approved

#718 chore: update github actions
  .github/workflows/e2e.yaml
Labels: size/S, lgtm, cncf-cla: yes, approved, kind/cleanup, ok-to-test

#713 Restore uber-go/mock.
  README.md
  go.mod
  go.sum
  pkg/server/backend_manager_test.go
  pkg/server/server_test.go
  proto/agent/mocks/agent_mock.go
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/go.uber.org/mock/AUTHORS
  vendor/go.uber.org/mock/LICENSE
  vendor/go.uber.org/mock/gomock/call.go
  vendor/go.uber.org/mock/gomock/callset.go
  vendor/go.uber.org/mock/gomock/controller.go
  vendor/go.uber.org/mock/gomock/doc.go
  vendor/go.uber.org/mock/gomock/matchers.go
  vendor/go.uber.org/mock/gomock/string.go
  vendor/modules.txt
Labels: lgtm, cncf-cla: yes, approved, size/XL

#714 Advance e2e test matrix (remove v1.28 and add v1.31).
  .github/workflows/e2e.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved

#720 Release v0.31 Cherry picked back missing v0.31.1 PR - KNP agent should pick the larger of the two server count
  cmd/agent/app/options/options.go
  cmd/agent/app/options/options_test.go
  cmd/agent/app/server.go
  cmd/server/app/options/options.go
  cmd/server/app/server.go
  pkg/agent/clientset.go
  pkg/agent/clientset_test.go
  pkg/agent/lease_counter.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#690 Switching to a longer test timeout.
  tests/concurrent_client_request_test.go
  tests/framework/agent.go
  tests/framework/proxy_server.go
  tests/framework/util.go
  tests/proxy_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#700 refactor: simplify ClientSet and add comments
  pkg/agent/clientset.go
Labels: size/S, lgtm, cncf-cla: yes, approved
